//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faat.Client.FaatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaatServiceReference.IFaatService")]
    public interface IFaatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/GetPage", ReplyAction="http://tempuri.org/IFaatService/GetPageResponse")]
        string GetPage(string identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/SetPage", ReplyAction="http://tempuri.org/IFaatService/SetPageResponse")]
        void SetPage(string identity, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaatServiceChannel : Faat.Client.FaatServiceReference.IFaatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaatServiceClient : System.ServiceModel.ClientBase<Faat.Client.FaatServiceReference.IFaatService>, Faat.Client.FaatServiceReference.IFaatService {
        
        public FaatServiceClient() {
        }
        
        public FaatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPage(string identity) {
            return base.Channel.GetPage(identity);
        }
        
        public void SetPage(string identity, string content) {
            base.Channel.SetPage(identity, content);
        }
    }
}
