//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faat.Client.FaatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaatServiceReference.IFaatService", CallbackContract=typeof(Faat.Client.FaatServiceReference.IFaatServiceCallback))]
    public interface IFaatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/GetData", ReplyAction="http://tempuri.org/IFaatService/GetDataResponse")]
        string GetData(string identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/SetData", ReplyAction="http://tempuri.org/IFaatService/SetDataResponse")]
        void SetData(string identity, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/Subscribe", ReplyAction="http://tempuri.org/IFaatService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/PingServer", ReplyAction="http://tempuri.org/IFaatService/PingServerResponse")]
        string PingServer(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/OnDataChanged", ReplyAction="http://tempuri.org/IFaatService/OnDataChangedResponse")]
        void OnDataChanged(string identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaatService/PingClient", ReplyAction="http://tempuri.org/IFaatService/PingClientResponse")]
        string PingClient(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaatServiceChannel : Faat.Client.FaatServiceReference.IFaatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaatServiceClient : System.ServiceModel.DuplexClientBase<Faat.Client.FaatServiceReference.IFaatService>, Faat.Client.FaatServiceReference.IFaatService {
        
        public FaatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FaatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FaatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FaatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FaatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GetData(string identity) {
            return base.Channel.GetData(identity);
        }
        
        public void SetData(string identity, string data) {
            base.Channel.SetData(identity, data);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public string PingServer(string message) {
            return base.Channel.PingServer(message);
        }
    }
}
